version: "3.7"
services:

  ezcloud-ops:
    image: e-flask
    privileged: true
    container_name: e-flask
    restart: always
    environment:
      FLASK_APP: production
    ports:
      - 2333:2333
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - internal

networks:
  internal:
    external: true
